### ISSUE TITLE
Colorizer Wand breaks bedrock

### ISSUE THREAD

**Issue by WenXin20** [grim3212/AssortedDecor#4]
`Assorted Tools v2.2.9`
`Minecraft v1.16.5`
`Forge v36.0.1`

The colorizer wand can instantly break through blocks such as obsidian and bedrock, which would normally take time or be impossible to break.

**Comment by grim3212** [comment]
Definitely an issue, I think at least for obsidian it might make sense to keep it the same but I think just disallowing bedrock should work.

**Comment by WenXin20** [comment]
Alright. A whitelist/blacklist could work, or maybe a tag. And then the user could add obsidian to the list of they wanted to.

**Comment by grim3212** [comment]
Yeah, exactly though I think there is already a list to disable/enable but I might be misremembering. Been on vacation for awhile. Either way what I was thinking for bedrock at least is if the config option for breaking blocks is active then you won't be able to use any unbreakable blocks.

As for obsidian and other hard blocks I think you should still be able to consume them because they are still breakable. Just with the way it is currently setup I'm not sure how you would make it so that it takes longer which is why I am focusing on unbreakable blocks like bedrock.

**Comment by WenXin20** [comment]
Ah, true

**Comment by grim3212** [comment]
Okay, the latest release should now have these features.
