### ISSUE TITLE
Colorized Brush crashing game "unclosed"

### ISSUE THREAD

**Issue by judicius** [grim3212/AssortedDecor#5]
Crash occurs when the colorizing brush would show up in JEI. Hiding the brush in JEI seems to temporarily fix it.

Assorted Decor 2.0.9
MC 1.16.5
Forge 3.6.1.4

crash log
https://gist.github.com/judicius/4b57909ff24901461792a1b29626064b

**Comment by WenXin20** [comment]
Hello, I got the same crash. It also crashes when middle-clicking a colorizer block. This happens if [Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) is installed.
https://gist.githubusercontent.com/natanfudge/b60a447424e46c7dda12ede0fcf56851/raw/6ede6e5d6b4910fbafe00e1147472b651310de3d/crash.txt

**Comment by grim3212** [comment]
My environment apparently is broken. I think I have a fix that will work but I am unable to build right now...

Will take a look once I have some more time

**Comment by WenXin20** [comment]
Jm________________________________Sincerely, David Newville

**Comment by WenXin20** [comment]
Thanks!

**Comment by grim3212** [comment]
Alright it should be fixed with 6970025.
It is published in `assorteddecor-1.16.5-2.0.10`
